package kit

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/neoighodaro/blvckhole/internal/config"
	"github.com/neoighodaro/blvckhole/internal/embedded"
)

func Generate(cfg *config.Config, kitDir string) error {
	if err := os.RemoveAll(kitDir); err != nil {
		return fmt.Errorf("failed to clean kit directory: %w", err)
	}
	if err := os.MkdirAll(kitDir, 0755); err != nil {
		return fmt.Errorf("failed to create kit directory: %w", err)
	}

	spec := buildSpec(cfg)
	if err := os.WriteFile(filepath.Join(kitDir, "spec.yaml"), []byte(spec), 0644); err != nil {
		return fmt.Errorf("failed to write spec.yaml: %w", err)
	}

	if err := writeKitFiles(cfg, kitDir); err != nil {
		return err
	}

	return nil
}

func buildSpec(cfg *config.Config) string {
	var b strings.Builder

	b.WriteString("schemaVersion: \"1\"\n")
	b.WriteString("kind: mixin\n")
	b.WriteString(fmt.Sprintf("name: blvckhole-%s\n", cfg.Name))
	b.WriteString("description: \"Generated by blvckhole\"\n")

	if len(cfg.MergedEnv) > 0 {
		b.WriteString("\nenvironment:\n")
		b.WriteString("  variables:\n")
		keys := make([]string, 0, len(cfg.MergedEnv))
		for k := range cfg.MergedEnv {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("    %s: %q\n", k, cfg.MergedEnv[k]))
		}
	}

	if len(cfg.Network) > 0 {
		b.WriteString("\nnetwork:\n")
		b.WriteString("  allowedDomains:\n")
		for _, domain := range cfg.Network {
			b.WriteString(fmt.Sprintf("    - %q\n", domain))
		}
	}

	if strings.TrimSpace(cfg.Memory) != "" {
		b.WriteString("\nmemory: |\n")
		for _, line := range strings.Split(cfg.Memory, "\n") {
			if line == "" {
				b.WriteString("\n")
			} else {
				b.WriteString("  " + line + "\n")
			}
		}
	}

	return b.String()
}

func writeKitFiles(cfg *config.Config, kitDir string) error {
	homeDir := filepath.Join(kitDir, "files", "home")
	claudeDir := filepath.Join(homeDir, ".claude")
	themeDir := filepath.Join(claudeDir, "themes")

	if err := os.MkdirAll(themeDir, 0755); err != nil {
		return fmt.Errorf("failed to create theme directory: %w", err)
	}

	if err := os.WriteFile(filepath.Join(homeDir, ".zshrc"), embedded.ZshrcSh, 0644); err != nil {
		return fmt.Errorf("failed to write .zshrc: %w", err)
	}
	aliasContent := make([]byte, len(embedded.ZshrcAliasesSh))
	copy(aliasContent, embedded.ZshrcAliasesSh)
	if len(cfg.Shell.Aliases) > 0 {
		keys := make([]string, 0, len(cfg.Shell.Aliases))
		for k := range cfg.Shell.Aliases {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		aliasContent = append(aliasContent, '\n')
		for _, k := range keys {
			aliasContent = append(aliasContent, []byte(fmt.Sprintf("alias %s=%q\n", k, cfg.Shell.Aliases[k]))...)
		}
	}
	if err := os.WriteFile(filepath.Join(homeDir, ".zshrc_aliases"), aliasContent, 0644); err != nil {
		return fmt.Errorf("failed to write .zshrc_aliases: %w", err)
	}

	themeData := embedded.ThemeJSON
	if cfg.Claude.Theme != "" {
		themePath := cfg.Claude.Theme
		if !filepath.IsAbs(themePath) {
			themePath = filepath.Join(cfg.ProjectDir, themePath)
		}
		custom, err := os.ReadFile(themePath)
		if err != nil {
			return fmt.Errorf("cannot read custom theme %s: %w", cfg.Claude.Theme, err)
		}
		themeData = custom
	}
	if err := os.WriteFile(filepath.Join(themeDir, "sandbox.json"), themeData, 0644); err != nil {
		return fmt.Errorf("failed to write theme: %w", err)
	}

	settingsData, err := mergeSettings(cfg)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(claudeDir, "settings.sandbox.json"), settingsData, 0644); err != nil {
		return fmt.Errorf("failed to write settings: %w", err)
	}

	if err := os.WriteFile(filepath.Join(claudeDir, "claude-dashboard.local.json"), embedded.DashboardJSON, 0644); err != nil {
		return fmt.Errorf("failed to write dashboard config: %w", err)
	}

	return nil
}

func mergeSettings(cfg *config.Config) ([]byte, error) {
	var defaults map[string]interface{}
	if err := json.Unmarshal(embedded.SettingsJSON, &defaults); err != nil {
		return nil, fmt.Errorf("failed to parse default settings: %w", err)
	}

	for k, v := range cfg.Claude.Settings {
		defaults[k] = v
	}

	data, err := json.MarshalIndent(defaults, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal settings: %w", err)
	}
	return data, nil
}
